### ISSUE TITLE
can Phrase cli trigger the auto-fill translation when push 

### ISSUE THREAD

**Issue by MichaelMaIkea** [phrase/phrase-cli#103]
when we push the source translation file to the phrase, and then pull, we expect the target files are all updated with auto-filled translated text by phrase. Do you know how to achieve that?

**Comment by theSoenke** [comment]
Hey @MichaelMaIkea, in the push configuration you can set `autotranslate` to `true`. All other upload options can be set like this as well in the params: https://developers.phrase.com/api/#post-/projects/-project_id-/uploads

For example:
```yaml
  push:
    sources:
      -
        file: ./en.yml
        params:
          locale_id: en
          autotranslate: true
```

Also autotranslate needs to be enabled in the project settings and then everything should be autotranslated on the next push.
