### ISSUE TITLE
How to phrase force push / overwrite?

### ISSUE THREAD

**Issue by WaKeMaTTa** [phrase/phrase-cli#108]
I tried to find out how to force push using phrase v2 cli in the documentation:

- https://phrase.com/cli/
- https://help.phrase.com/help/phrase-in-your-terminal
- https://developers.phrase.com/api

but I don't find a way.

**Comment by forelabs** [comment]
Hi @WaKeMaTTa,

what exactly do you mean by `force`?
Our push and pull commands are not protected in any way so pulling will override and pushing as well.

You can specify a parameter for pushing to either update translations (default) or not:

```
push:

    sources:

    - file: ./locales/en.json

       params:

        update_translations: true 
```

https://help.phrase.com/help/configuration
