### ISSUE TITLE
Bad Request if `fallback_locale_id` is present

### ISSUE THREAD

**Issue by mmdumi** [phrase/phrase-cli#126]
Hi,
I just saw today that my phrase cli script doesn't work any more. I tried even with the latest phrase cli executable but it's the same. I guess that the issue is server side.
Including the `fallback_locale_id` throws ERROR: 400 Bad Request
Example of pull configuration:

```
  pull:
    targets:
    - file: ./<locale_code>.lproj/Localizable.strings
      params:
        file_format: strings
        encoding: UTF-8
        include_empty_translations: true
        fallback_locale_id: 'en'
```

Removing fallback_locale_id works ok, but I really need it to be set
