### ISSUE TITLE
Phrase CLI returns unhelpful "ERROR: 404 Not Found" with no details

### ISSUE THREAD

**Issue by rlundy** [phrase/phrase-cli#141]
I'm trying the command `phrase push -w`, and I get back

> ERROR: 404 Not Found

If I use `phrase push -w -v` instead, I get more data [shown below, redacted], but still no useful error message:

```
>phrase push -w -v
&{Credentials:{Username: Token:[OMITTED] TFA:false TFAToken: Host:} Debug:true Page:<nil> PerPage:<nil> DefaultProjectID:[OMITTED] DefaultFileFormat: Defaults:map[] Targets:[OMITTED] Sources:[OMITTED] UserAgent:Phrase Strings CLI (2.22.0)}
ERROR: 404 Not Found
```

What would be more useful is an explanation of why the 404 happened.  What address was I trying to reach that doesn't exist?

**Comment by rlundy** [comment]
I tried Fiddler to see what URL it was trying to hit and there's nothing there, even if I tell it to intercept and decrypt HTTPS.  When I run the Phrase CLI, it isn't making an entry in the Fiddler list.

**Comment by jablan** [comment]
Hi @rlundy thanks for reporting this, the error is indeed not telling much. We will open an internal task to improve on this.

In the meantime, could you double check your project ID in your phrase.yml configuration?

**Comment by rlundy** [comment]
I've confirmed that the project ID is correct.  Our phrase.yml file looks like this (but with the correct project ID, of course):

```
phrase:
  project_id: REDACTED
  push:
    sources:
      - file: ./src/assets/locales/<locale_name>.json
        params:
          file_format: i18next
  pull:
    targets:
      - file: ./src/assets/locales/<locale_name>.json
        params:
          file_format: i18next
```

**Comment by rlundy** [comment]
Correct, we're using app.phrase.com, EU data center.  We're based in Switzerland.

**Comment by rlundy** [comment]
Doubtless worth noting is that some Phrase CLI commands do work correctly.  If I use

`phrase users user`

for example, I do get back the details of my user.

**Comment by rlundy** [comment]
I also tried adding `host:` to the .yml file:

```
phrase:
  host: https://api.phrase.com/v2/
  project_id: REDACTED
  [...etc...]
```

But this gave me the same results; `phrase users user` works but `phrase push -w -v` gives a 404 with no other info.
