### ISSUE TITLE
[2.31.0] ERROR: invalid argument

### ISSUE THREAD

**Issue by backslash-f** [phrase/phrase-cli#151]
What does `ERROR: invalid argument for [redacted]/Resources/Localization/de.lproj/Localizable.strings` mean?

The command I'm using:
```bash
phrase pull -t <token> --verbose
```

The output:
```bash
&{Credentials:{Username: Token:[redacted] TFA:false TFAToken: Host:} Debug:true Page:<nil> PerPage:<nil> DefaultProjectID:[redacted]DefaultFileFormat: Defaults:map[] Targets:[] Sources:[] UserAgent:Phrase Strings CLI (2.31.0)}
Target file pattern: [redacted]/Resources/Localization/<locale_code>.lproj/Localizable.strings
Actual file path [redacted]/Resources/Localization/de.lproj/Localizable.strings
LocaleID [redacted]
ProjectID [redacted]
FileFormat {true strings}
ConvertEmoji {false false}
IncludeEmptyTranslations {false false}
KeepNotranslateTags {false false}
Tags {false }
Branch {false }
FormatOptions {false <nil>}

ERROR: invalid argument for [redacted]/Resources/Localization/de.lproj/Localizable.strings
```

My `.phraseapp.yml` file:
```yaml
---
phraseapp:
  project_id: [redacted]
  pull:
    targets:
      - file: [redacted]/Resources/Localization/<locale_code>.lproj/Localizable.strings
        params:
          file_format: strings
```

Note 1: If I manually download the `de` language from Phrase's website as `Localizable.strings`, it comes empty, which is fine, as there are no German translations (yet). I wonder if this is what's causing the error...

Note 2: `[redacted]` <<== something I'm manually adding **here**, to hide sensitive info.
