### ISSUE TITLE
Support of xcstrings catalog export option

### ISSUE THREAD

**Issue by JAIRMG** [phrase/phrase-cli#154]
Hi hi, according to https://developer.apple.com/videos/play/wwdc2023/10155/?time=1679 there is a new way to work with strings on iOS side. I noticed that .strings files are deprecated in later Xcode versions. I am wondering if there is a plan to introduce this change and allow download .xcstrings directly. 

Thanks!

**Comment by JAIRMG** [comment]
Thanks for the quick response! happy to hear that. I'm looking forward for that implementation.

**Comment by albertodebortoli** [comment]
Hi @forelabs, is there any update on supporting the `xcstrings` format?

**Comment by forelabs** [comment]
Hi @albertodebortoli,

while I can not give an ETA yet we do plan to work on it. It is listed on our roadmap as a potential next item to work on. I will get back here ones we know when it will be worked on.

Thanks for your feedback. If your company has not yet send this request to your account manager or the support, please let them know so we do understand how many of our customers are requesting this. Thank you.

**Comment by jablan** [comment]
hey @JAIRMG @albertodebortoli you may want to know that xcstrings support has been added last month: https://support.phrase.com/hc/en-us/articles/18807352792604--XCSTRINGS-Apple-Strings-Catalog-Strings

**Comment by ValentinDenis** [comment]
Hi @jablan & @forelabs 

There seems to be an issue with pulling translations from CLI using `.xcstrings` format
I get this error : 

> ERROR: Could not find any locale information. Please specify a 'locale_id' in your params or provide a placeholder (<locale_code|locale_name>)

Here is my yml : 

```
phrase:
  access_token: XXX
  project_id: XXX
  push:
    sources:
    - file: XXX/Resources/Localizables/Localizable.xcstrings
      params:
        autotranslate: true
        file_format: strings_catalog
        tags: Localizable
    - file: XXX/Resources/Localizables/InfoPlist.xcstrings
      params:
        autotranslate: true
        file_format: strings_catalog
        tags: InfoPlist
  pull:
    targets:
    - file: XXX/Resources/Localizables/Localizable.xcstrings
      params:
        file_format: strings_catalog
        tags: Localizable
    - file: XXX/Resources/Localizables/InfoPlist.xcstrings
      params:
        file_format: strings_catalog
        tags: InfoPlist
```

Shouldn't the language code be infered from the json in .xcstrings by the cli? How do I map them ?

Thanks for your help

**Comment by forelabs** [comment]
Hi @ValentinDenis,

while we do support the file format the CLI (and API) have not received an option that would allow to download all available languages. Actually, our download endpoint still requires a main locale you pass for the download followed by additional locales that should be part of the file. Sadly this means you have to mention all languages. We will add a roadmap item to improve this and most likely introduce an option to download all locales at ones without explicity naming them.

Right now, it should work like this:

```yml
phrase:
  access_token: XXX
  project_id: XXX
  push:
    sources:
    - file: XXX/Resources/Localizables/Localizable.xcstrings
      params:
        autotranslate: true
        file_format: strings_catalog
        tags: Localizable
    - file: XXX/Resources/Localizables/InfoPlist.xcstrings
      params:
        autotranslate: true
        file_format: strings_catalog
        tags: InfoPlist
  pull:
    targets:
    - file: XXX/Resources/Localizables/Localizable.xcstrings
      params:
        file_format: strings_catalog
        tags: Localizable
        locale_id: en # name the "main" language used for the download
        locale_ids: de, fr, it, es # name all languages that should additional be included in the file
    - file: XXX/Resources/Localizables/InfoPlist.xcstrings
      params:
        file_format: strings_catalog
        tags: InfoPlist
        locale_id: en # name the "main" language used for the download
        locale_ids: de, fr, it, es # name all languages that should additional be included in the file
```

**Comment by ValentinDenis** [comment]
Thanks ! 
It works like a charm

For your information, if you add spaces in the list of "locale_ids", it only imports the first one
If you remove the spaces, it imports all listed languages

Here is the correct format : 

```
phrase:
  access_token: XXX
  project_id: XXX
  push:
    sources:
    - file: XXX/Resources/Localizables/Localizable.xcstrings
      params:
        autotranslate: true
        file_format: strings_catalog
        tags: Localizable
    - file: XXX/Resources/Localizables/InfoPlist.xcstrings
      params:
        autotranslate: true
        file_format: strings_catalog
        tags: InfoPlist
  pull:
    targets:
    - file: XXX/Resources/Localizables/Localizable.xcstrings
      params:
        file_format: strings_catalog
        tags: Localizable
        locale_id: en # name the "main" language used for the download
        locale_ids: de,fr,it,es # name all languages that should additional be included in the file
    - file: XXX/Resources/Localizables/InfoPlist.xcstrings
      params:
        file_format: strings_catalog
        tags: InfoPlist
        locale_id: en # name the "main" language used for the download
        locale_ids: de,fr,it,es # name all languages that should additional be included in the file
```
