### ISSUE TITLE
CLI 2.0 breaks the support of YAML anchors and aliases 

### ISSUE THREAD

**Issue by volo-droid** [phrase/phrase-cli#23]
To avoid repetitions in YAML config, we've been using the config with YAML [anchors and aliases](http://blogs.perl.org/users/tinita/2019/05/reusing-data-with-yaml-anchors-aliases-and-merge-keys.html). Our config looks like this (in real project we have many more modules):

```yaml
VALUES: &PARAMS_MAP
  include_empty_translations: true
  format_options: { convert_placeholder: true, escape_linebreaks: true }
  fallback_locale_id: en

phraseapp:
  access_token: 012345678901234567890
  project_id: 012345678901234567890
  file_format: xml

  pull:
    targets:

      - file: ./app/src/main/res/<locale_name>/app_strings.xml
        params:
          tags: "android_app"
          <<: *PARAMS_MAP

      - file: ./common/src/main/res/<locale_name>/common_strings.xml
        params:
          tags: "android_common"
          <<: *PARAMS_MAP

      - file: ./feature_a/src/main/res/<locale_name>/fta_strings.xml
        params:
          tags: "android_feature_a"
          <<: *PARAMS_MAP

      - file: ./feature_b/src/main/res/<locale_name>/ftb_strings.xml
        params:
          tags: "android_feature_b"
          <<: *PARAMS_MAP
```

This works in `phraseapp` CLI v1.6.1, but `phrase` CLI v2.0.13 fails with the following error:
> Error: configuration key "fallback_locale_id" unknown
> see https://help.phrase.com/articles/2185247-configuration

**Comment by volodymyr-gz** [comment]
Actually this has been broken back in 1.17.0 😲, 1.16.1 was the last version that correctly supported anchors
I'm not sure you need that info, but to summarize:

Works in
 ```
PhraseApp client version:            1.16.1
PhraseApp client revision:           d1fb5cafb262989b0ba36d1efcf5f7c98c1227c1
PhraseApp library revision:          14bf46b95f02
Last change at:                      Mon Nov 25 14:07:11 2019 +0100
Go version:                          go1.11.13
```

Broken in
```
PhraseApp client version:            1.17.0
PhraseApp client revision:           5b939ab2082b25b00130af18ceff385462ca5679
PhraseApp library revision:          14bf46b95f02
Last change at:                      Mon Mar 30 11:43:26 2020 +0200
Go version:                          go1.11.13
```
and 
```
Phrase client version:               2.0.13
Phrase client revision:              72a3b80ea91885b998de44a0199e353b419b9c69
Phrase library revision:             v1.0.10/go.mod
Last change at:                      Mon Aug 3 09:34:49 2020 +0000
Go version:                          go1.14.6
```

**Comment by volodymyr-gz** [comment]
And this is the change that caused it: 

https://github.com/phrase/phraseapp-client/commit/b8656eafc7ba52d4dd0d4a557aa3e0d657b73f05?branch=b8656eafc7ba52d4dd0d4a557aa3e0d657b73f05&diff=unified#diff-caa376669c397f9e1425fce40d0a57c8L33-R34

**Comment by volodymyr-gz** [comment]
Today version 1.16.1 stopped working with an error:
```
ERROR: {"message":"Not Found","documentation_url":"https://developers.phrase.com/api/#get-/projects/{project_id}/locales"}
```

@rlisowski We need to find a workaround for this issue at our project. Can you comment on how to use a `defaults` section?

**Comment by rlisowski** [comment]
@volodymyr-gz are you sure you have correct locale_id in config file? `ERROR: {"message":"Not Found","documentation_url":"https://developers.phrase.com/api/#get-/projects/{project_id}/locales"}` looks like missing locale mesage.

**Comment by rlisowski** [comment]
also, anchors are supported but not on top-level since we do not expect `VALUES:` there, as a workaround you can define anchor first time when you use it and then just refer to it eg:

```
phraseapp:
  access_token: 012345678901234567890
  project_id: 012345678901234567890
  file_format: xml

  pull:
    targets:

      - file: ./app/src/main/res/<locale_name>/app_strings.xml
        params: &PARAMS_MAP
          tags: "android_app"
          include_empty_translations: true
          format_options: { convert_placeholder: true, escape_linebreaks: true }
          fallback_locale_id: en

      - file: ./common/src/main/res/<locale_name>/common_strings.xml
        params:
          <<: *PARAMS_MAP
          tags: "android_common"

      - file: ./feature_a/src/main/res/<locale_name>/fta_strings.xml
        params:
          <<: *PARAMS_MAP
          tags: "android_feature_a"

      - file: ./feature_b/src/main/res/<locale_name>/ftb_strings.xml
        params:
          <<: *PARAMS_MAP
          tags: "android_feature_b"
```
