### ISSUE TITLE
Feature request: Allow explicit exclusion of locales in CLI & its yml file

### ISSUE THREAD

**Issue by GeroHerkenrath** [phrase/phrase-cli#41]
This has come up in two other (now closed) issues, so I'll add a new request for this.
I'd really appreciate it if I could exclude specific locales from `push` and `pull` when using the CLI, at least when pulling. I could imagine something like this for the YAML config file:

```
phraseapp:
  file_format: xml
  project_id: ...
  pull:
    targets:
    - file: ./app/src/main/res/values-<locale_code>/strings.xml
      params:
        exclude: en
  push:
    sources:
    - file: ./app/src/main/res/values/strings.xml
      params:
        locale_id: ...
```

The `exclude` part would be new, I wouldn't care much how the locale is specified there (it could also be the id, like in the `push` section). The reason why I cannot just "whilelist" the other locales instead of excluding that one would be that I don't necessarily know how many locales there are. Those should be added by our localizers directly in PhraseApp, without having the need to update the YAML.

The related issues were phrase/phraseapp-client#12 and phrase/phraseapp-client#27. I am in a similar position, i.e. I don't want to `pull` the default language/locale in an Android project. As above YAML shows, instead I also only `push` said default. 

That way, we have a "single point of truth" for the "input" for our localization team. They also use git sync, so PhraseApp actually does the `pull` for us most of the time. It's not a big deal having the default language kind of "doubled" in the project (once as default, once as explicit en locale in `./app/src/main/res/values-en/strings.xml` after a `pull`), but it would be cleaner and nicer to be able to omit that. Currently we devs manually go into the PRs created via PhraseApp, delete the superfluous en locale, commit & push and then merge the PR, but I see the day coming we forget that. 😄
