### ISSUE TITLE
[Request] Pull all tags

### ISSUE THREAD

**Issue by sylfabre** [phrase/phrase-cli#42]
Usecase:
- I want to keep my folder structure as per https://help.phraseapp.com/en/articles/2136270-structuring-translations-how-to-keep-the-original-files
- I'm using tags on PhraseApp as equivalent to my Symfony domains
- I have one Symfony domain per view (so the translation file is not too big)
- So I have a lot of tags and I keep adding new ones
- I want to use the PhraseApp client in my CI/CD process

Right now, I have to create a configuration file where I list all my tags:

```yaml
phraseapp:
  access_token: "some token"
  project_id: "some project id"
  file_format: yml
  pull:
    targets:
      - file: ./translations/<tag>.<locale_name>.yml
        params:
          tags: tag1, tag2, ....
````

I would like to have a way to say "all tags", for instance:
```yaml
phraseapp:
  access_token: "some token"
  project_id: "some project id"
  file_format: yml
  pull:
    targets:
      - file: ./translations/<tag>.<locale_name>.yml
        params:
          tags: "*"
````

**Comment by jakubgereg** [comment]
Ive came across to the same problem. Then question is why there is parameter called 'tags' if it can have only one tag.

 
```yml
push:
    sources:
    - file: ./public/locales/<locale_name>/<tag>.json
      params:
        file_format: i18next
  pull:
    targets:
    - file: ./public/locales/<locale_name>/<tag>.json
      params:
        file_format: i18next
        tags: 'common'
        
```
And why the push command works fine and it can recognise multiple tags, but for pull you have to target it one by one.
Is there any solution to this ?
