### ISSUE TITLE
Empty stringsdict on phrase pull

### ISSUE THREAD

**Issue by kayoslab** [phrase/phrase-cli#50]
# Precondition
- Creating a new Phrase project.
- Adding keys to the project and translating them
- Installing the latest version of the phrase CLI tool.
- Running the `phrase init` for the new project selecting output style 8 (stringsdict).

# Expected Result:
- The stringsdict contains the keys added to the phrase project

# Actual Result:
- The stringsdict stays empty.
- When running the same configuration with a different `file_format` (e.g. json) the keys are loaded correctly and written as JSON.

Content of the `./<ProjectName>/Translations/<locale_code>.lproj/Localizable.stringsdict` file.
```
<?xml version="1.0" encoding="UTF-8"?>
<plist version="1.0">
  <dict/>
</plist>

```

# Configurations:

Result of `phrase info` call:
```
Phrase client version:            2.0.15
Phrase client revision:           1873a78ea3a7c66cf9c74b3bfd4ac8710aef6f53
Phrase library revision:          v1.0.11/go.mod
Last change at:                   Mon Oct 19 09:41:24 2020 +0000
Go version:                       go1.14.10
```

Content of the `.phrase.yml` file:
```
phrase:
  access_token: <token>
  project_id: <project>

  push:
    sources:
    - file: ./<ProjectName>/Translations/<locale_code>.lproj/Localizable.stringsdict
      params:
        file_format: stringsdict
  pull:
    targets:
    - file: ./<ProjectName>/Translations/<locale_code>.lproj/Localizable.stringsdict
      params:
        file_format: stringsdict
```

Result of `phrase -v pull` obfuscated:
```
UserAgent:Phrase CLI (2.0.15)}
Target file pattern: ./<ProjectName>/Translations/<locale_code>.lproj/Localizable.stringsdict
Actual file path <path>/<ProjectName>/Translations/de.lproj/Localizable.stringsdict
LocaleID <LocaleID>
ProjectID <ProjectID>
FileFormat {true stringsdict}
ConvertEmoji {false false}
IncludeEmptyTranslations {false false}
KeepNotranslateTags {false false}
Tag {false }
Branch {false }
FormatOptions {false <nil>}
Downloaded de to <ProjectName>/Translations/de.lproj/Localizable.stringsdict
----------
Target file pattern: ./<ProjectName>/Translations/<locale_code>.lproj/Localizable.stringsdict
Actual file path <path>/<ProjectName>/Translations/de.lproj/Localizable.stringsdict
LocaleID <LocaleID>
ProjectID <ProjectID>
FileFormat {true stringsdict}
ConvertEmoji {false false}
IncludeEmptyTranslations {false false}
KeepNotranslateTags {false false}
Tag {false }
Branch {false }
FormatOptions {false <nil>}
Downloaded de to <ProjectName>/Translations/en.lproj/Localizable.stringsdict
```
