### ISSUE TITLE
phraseupp will delete a key if string is empty

### ISSUE THREAD

**Issue by Wendenburg** [phrase/phrase-cli#63]
Example:
// bar is not needed for this language
{
   foo: 'my phrase',
   bar: '' 
}

after phraseapp push and pull again json for this language will look like
{
   foo: 'my phrase'
}

Expected result is that the key is not deleted from the json file.

**Comment by theSoenke** [comment]
Hi @Wendenburg, empty translations are not exported by default but there is a option `include_empty_translations: true` to keep them. 

```yml
phrase:
  file_format: simple_json
  pull:
    targets:
      -
        file: ./app/<locale_name>.json
        project_id: <PROJECT_ID>
        params:
          include_empty_translations: true
```

Let me know this already helps.
