### ISSUE TITLE
phrase pull – panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by t-unit** [phrase/phrase-cli#76]
We are having a fairly complex setup for a Flutter application. When trying to pull translations for `./ios/Runner/<locale_code>.lproj/InfoPlist.strings` we run into the following error. Pushing works fine, also pulling when commenting out the file in question.

```bash
phrase pull
Downloaded de to android/app/src/main/res/values-de/strings.xml
Downloaded en to android/app/src/main/res/values/strings.xml
Downloaded de to android/app/src/main/res/values-de/strings.xml
Downloaded en to android/app/src/main/res/values/strings.xml
Downloaded de to assets/strings/intl_de.arb
Downloaded en to assets/strings/intl_en.arb
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x14d1197]

goroutine 1 [running]:
os.(*File).Name(...)
	/usr/local/go/src/os/file.go:55
github.com/phrase/phrase-cli/cmd/internal.(*Target).DownloadAndWriteToFile(0xc0002ba960, 0xc000127540, 0xc0004be000, 0x0, 0x0, 0x0, 0x2)
	/go/src/github.com/phrase/phrase-cli/cmd/internal/pull.go:179 +0x2d7
github.com/phrase/phrase-cli/cmd/internal.(*Target).Pull(0xc0002ba960, 0xc000127540, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/phrase/phrase-cli/cmd/internal/pull.go:121 +0x19d
github.com/phrase/phrase-cli/cmd/internal.(*PullCommand).Run(0xc00016dcb8, 0xc000290000, 0x15, 0x0)
	/go/src/github.com/phrase/phrase-cli/cmd/internal/pull.go:72 +0x48f
github.com/phrase/phrase-cli/cmd.initPull.func1(0xc00027e2c0, 0x1a4d680, 0x0, 0x0)
	/go/src/github.com/phrase/phrase-cli/cmd/pull.go:24 +0xef
github.com/spf13/cobra.(*Command).execute(0xc00027e2c0, 0x1a4d680, 0x0, 0x0, 0xc00027e2c0, 0x1a4d680)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x1a14960, 0x101a501, 0x0, 0x0)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/phrase/phrase-cli/cmd.Execute()
	/go/src/github.com/phrase/phrase-cli/cmd/root.go:64 +0x2d
main.main()
	/go/src/github.com/phrase/phrase-cli/main.go:8 +0x25
```

our `.phrase.yml`
```yaml
phrase:
  access_token: [...]
  project_id: [...]
  push:
    sources:
    - file: ./android/app/src/main/res/values/strings.xml
      params: 
        file_format: xml
        locale_id: 15b158324c59c8e41f25291f0db1f9d9
        tags: push
        update_translations: false
    - file: ./assets/strings/intl_en.arb
      params:
        update_translations: false
        locale_id: en
        file_format: arb
    - file: ./ios/Runner/en.lproj/Localizable.strings
      params:
        tags: push
        update_translations: false
        locale_id: en
        file_format: strings
    - file: ./ios/Runner/en.lproj/InfoPlist.strings
      params:
        tags: plist
        update_translations: false
        locale_id: en
        file_format: strings
  pull:
    targets:
    - file: ./android/app/src/main/res/values-de/strings.xml
      params:
        file_format: xml
        locale_id: b66a782309189fa5de792a030917c718
        tags: push
        format_options:
          convert_placeholder: true
    - file: ./android/app/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: 15b158324c59c8e41f25291f0db1f9d9
        tags: push
        format_options:
          convert_placeholder: true
    - file: ./android/app/src/main/res/values-de/strings.xml
      params:
        file_format: xml
        locale_id: b66a782309189fa5de792a030917c718
        tags: push
        format_options:
          convert_placeholder: true
    - file: ./android/app/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: 15b158324c59c8e41f25291f0db1f9d9
        tags: push
        format_options:
          convert_placeholder: true
    - file: ./assets/strings/intl_<locale_name>.arb
      params:
        file_format: arb
        format_options:
          convert_placeholder: true
    - file: ./ios/Runner/<locale_code>.lproj/InfoPlist.strings
      params:
        tags: plist
        file_format: strings
        format_options:
          convert_placeholder: true
    - file: ./ios/Runner/<locale_code>.lproj/Localizable.strings
      params:
        tags: push
        file_format: strings
        format_options:
          convert_placeholder: true
```

Used version:
```bash
% phrase info
Phrase client version:            2.1.3
Phrase client revision:           9fa1e035ee0ec440c31d4d5d4d50528a26a031c7
Phrase library revision:          v2.0.0/go.mod
Last change at:                   Thu Feb 25 13:37:56 2021 +0000
Go version:                       go1.16
```
